---
galaxy_info:
  author: Tung Ha
  description: cURL
  company: SmartOSC Corp. <http://www.smartosc.com>
  license: BSD
  min_ansible_version: 1.2
  platforms:
    # - name: EL
    #   versions:
    #   - all
    #   - 5
    #   - 6
    #   - 7
    # - name: GenericUNIX
    #   versions:
    #   - all
    #   - any
    # - name: Fedora
    #   versions:
    #   - all
    #   - 16
    #   - 17
    #   - 18
    #   - 19
    #   - 20
    # - name: SmartOS
    #   versions:
    #   - all
    #   - any
    # - name: opensuse
    #   versions:
    #   - all
    #   - 12.1
    #   - 12.2
    #   - 12.3
    #   - 13.1
    #   - 13.2
    # - name: Amazon
    #   versions:
    #   - all
    #   - 2013.03
    #   - 2013.09
    # - name: GenericBSD
    #   versions:
    #   - all
    #   - any
    # - name: FreeBSD
    #   versions:
    #   - all
    #   - 8.0
    #   - 8.1
    #   - 8.2
    #   - 8.3
    #   - 8.4
    #   - 9.0
    #   - 9.1
    #   - 9.1
    #   - 9.2
  - name: Ubuntu
    versions:
      - all
  #- name: SLES
  #  versions:
  #  - all
  #  - 10SP3
  #  - 10SP4
  #  - 11
  #  - 11SP1
  #  - 11SP2
  #  - 11SP3
  #- name: GenericLinux
  #  versions:
  #  - all
  #  - any
  - name: Debian
    versions:
      - all
  categories:
    # - cloud
    # - cloud:ec2
    # - cloud:gce
    # - cloud:rax
    # - clustering
    # - database
    # - database:nosql
    # - database:sql
    # - development
    # - monitoring
    # - networking
    # - packaging
    - system
    # - web
dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.

